LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams?limit=200000"
  NCAA_TEAMS:
    - "https://www.ncaa.com/stats/football/fcs/current/team/27"
    - "https://www.ncaa.com/stats/football/fcs/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/fcs/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/fbs/current/team/27"
    - "https://www.ncaa.com/stats/football/fbs/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/fbs/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/d2/current/team/27"
    - "https://www.ncaa.com/stats/football/d2/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/d2/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/d2/current/team/27/p4"
    - "https://www.ncaa.com/stats/football/d3/current/team/27"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p4"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p5"
  NCAA_COACHES:
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FBS_football_coaches"
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_II_football_coaches"
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_III_football_coaches"
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FCS_football_coaches"
  NCAA_IDS:
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=11.0&ranking_period=84.0&sport_code=MFB&stat_seq=22.0"
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=12.0&ranking_period=39.0&sport_code=MFB&stat_seq=27.0"
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=2.0&ranking_period=34.0&sport_code=MFB&stat_seq=27.0"
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=3.0&ranking_period=30.0&sport_code=MFB&stat_seq=27.0"
  FBS_VENUES: "https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_FBS_football_stadiums"
  FCS_VENUES: "https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_FCS_football_stadiums"
ATTRIBUTES:
  NCAA_TEAM_REF: "td.reclass a.skipMask[href^='/teams/']"
  NCAA_PAGINATION:
    SHOW_ALL_SELECTOR: "select[name*='length'] option[value='-1'], select[name*='length'] option:last-child"
  NCAA_TEAMS:
    ROWS: "table tr[class^='stats-table-row']"
    COLUMNS: "td"
    COLUMN_NUMBER: 1
    IMG_SRC: "img"
    SCHOOL_URL: "a[href^='/schools/']"
    SCHOOL_NAME: "a[href^='/schools/']"
  NCAA_DETAILED:
    CONFERENCE: "//dl[contains(@class, 'school-details')]//dt[text()='Conference']/following-sibling::dd"
    NICKNAME: "//dl[contains(@class, 'school-details')]//dt[text()='Nickname']/following-sibling::dd"
    COLORS: "//dl[contains(@class, 'school-details')]//dt[text()='Colors']/following-sibling::dd"
    SCHOOL: "//h1[contains(@class, 'school-name')]"
    WEBSITE: "//div[contains(@class, 'school-links')]//a[not(contains(@href, 'twitter.com')) and not(contains(@href, 'facebook.com')) and not(contains(@href, 'instagram.com'))]/@href"
    TWITTER: "//div[contains(@class, 'school-links')]//a[contains(@href, 'twitter.com')]/@href"
    DIVISION: ".division-location"
    SUB_DIVISION: '//*[@id="item-0"]/p'
  NCAA_STAT:
    HEAD_COACH: "//div[contains(@class,'card-header') and contains(text(), 'Coach')]/following-sibling::div//a"
    VENUE: "//div[contains(@class, 'card-header') and contains(text(), 'Stadium')]/following-sibling::div//dt[contains(text(), 'Name:')]/following-sibling::dd"
  VENUES:
    NAME: "//table[contains(@class,'infobox')]//caption"
    LOCATION: "//th[@class='infobox-label'][contains(., 'Location')]/following-sibling::td[1]"
    LATLON_DECIMAL: "//span[contains(@class, 'geo-dec')]/text()"
    SURFACE: "//th[@class='infobox-label'][contains(., 'Surface')]/following-sibling::td[1]"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FBS_football_coaches": 
    TABLE: "(//table)[1]"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FCS_football_coaches": 
    TABLE: "(//table)[2]"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_II_football_coaches": 
    TABLE: "(//table)[2]"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_III_football_coaches": 
    TABLE: "(//table)[1]"
